// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpRV5pV76OYmw9Ni5MoolEM7YpwOlwRhk',
    appId: '1:5306417515:web:9fc8d74890d70d8b44cc2e',
    messagingSenderId: '5306417515',
    projectId: 'gemastik-407fd',
    authDomain: 'gemastik-407fd.firebaseapp.com',
    storageBucket: 'gemastik-407fd.appspot.com',
    measurementId: 'G-LH0KEH1303',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv646dySHNEB_hDPklW3kZq0w9GEGEkCM',
    appId: '1:5306417515:android:d8b3c23401c043ac44cc2e',
    messagingSenderId: '5306417515',
    projectId: 'gemastik-407fd',
    storageBucket: 'gemastik-407fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHu4j-HH3yHYAh7shEErqURXY74CykYGs',
    appId: '1:5306417515:ios:db02bb5ec6a091be44cc2e',
    messagingSenderId: '5306417515',
    projectId: 'gemastik-407fd',
    storageBucket: 'gemastik-407fd.appspot.com',
    androidClientId: '5306417515-c5quth4n1ikpgj84ma9m6s2liqrt1n82.apps.googleusercontent.com',
    iosClientId: '5306417515-vg6i0691jtctedq6ee7tppd0bbj6n669.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectGemastik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHu4j-HH3yHYAh7shEErqURXY74CykYGs',
    appId: '1:5306417515:ios:4213cb9a0e3f82fb44cc2e',
    messagingSenderId: '5306417515',
    projectId: 'gemastik-407fd',
    storageBucket: 'gemastik-407fd.appspot.com',
    androidClientId: '5306417515-c5quth4n1ikpgj84ma9m6s2liqrt1n82.apps.googleusercontent.com',
    iosClientId: '5306417515-ddn2c3rcbamvl3snt08v0em2vr7pldk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectGemastik.RunnerTests',
  );
}
